Cards
HFG88/Episode-IV-A-New-Repo pull request #3
Opened 2024-10-09 13:15 UTC by Domald-d

bætti við nokkrum breytingum þurfti að setja nokkrar breytur í layout fyrir grid og card/cards  reyndi að setja engar font breytur etc   bætti samt við wrapper fyrir grid stillingar svo við fáum grid layout en getum breytt grid layoutinu seinna :)

2024-10-09 19:31 UTC, HFG88 requested changes
Ertu að runna stylelint á þetta? Ég veit ekki hvort það komi upp villa í því þegar breytur eru settar upp tvisvar en það eru breytur sem voru þegar komnar inn eins og vertical space og svona. Bilin eru ekki eins í þessu verkefni og í hinu. Svo er líka ekki þörf á litunum úr því

2024-10-10 10:27 UTC, Domald-d commented
Lint runnað og tvöfaldar breytur fjarlægðar sá þær ekki.
tók út liti og svoleiðis  er með bara placeholder  hvítan lit á grids sem má breyta seinna

2024-10-10 10:28 UTC, Domald-d commented
> Ertu að runna stylelint á þetta? Ég veit ekki hvort það komi upp villa í því þegar breytur eru settar upp tvisvar en það eru breytur sem voru þegar komnar inn eins og vertical space og svona. Bilin eru ekki eins í þessu verkefni og í hinu. Svo er líka ekki þörf á litunum úr því

Lint runnað og tvöfaldar breytur fjarlægðar sá þær ekki.
tók út liti og svoleiðis er með bara placeholder hvítan lit á grids sem má breyta seinna

2024-10-23 18:32 UTC, HFG88 requested changes
Nokkur comment. Ekki stór fix

2024-10-23 18:32 UTC, HFG88 commented on styles/config.scss
> -  --vertical-space-large: calc(var(--gutter) * 2);
Eigum við ekki að halda 40px breytunni? T.d. á milli latest recipes og hero, og svo kannski jafnvel á milli video section og book section (60 px sem má mín vegna fá sér breytu sem er calc(var(--gutter) * 3); en væri eflaust í lagi með bara sömu breytu)

2024-10-23 18:32 UTC, HFG88 commented on styles/layout.scss
> +  background-color: var(#fff);
background color: var(er ekki var)

2024-10-23 18:32 UTC, HFG88 commented on styles/layout.scss
> +  background-color: var(#fff);
Ég er ekki viss um að við þurfum þetta wrapper grid því ég hafði áður sett það í wrapper-content því ég var búinn að ráðstafa html öðruvísi en ég er ekki viss, svo þetta má mín vegna vera áfram og við pælum kannski í því seinna ef þetta verður eitthvað funky

2024-10-23 23:35 UTC, Domald-d commented on Myndir/pumpkinpie.jpg
fjarlægði layout/config scss svo að það conflicti ekki við það sem þú varst búinn að skrifa
er bara að pusha inn cards/card scss og grid.css

2024-10-24 11:39 UTC, HFG88 approved these changes
Flott. Veit einhver hvort þetta eyði út files úr main ef þau eru fjarlægð hér?
Ef ekki er ég að setja já á þetta

2024-10-24 12:17 UTC, merged